import Head from 'next/head'
import { Edu_TAS_Beginner } from 'next/font/google'
import MainPage from '@/components/mainPage'

const edu_tas_beginner = Edu_TAS_Beginner({
  weight: ['400', '500'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export default function Home() {
  return (
    <>
      <style jsx global>{`
        * {
          font-family: ${edu_tas_beginner.style.fontFamily};
        }
      `}</style>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main  >
        <MainPage />
      </main>
    </>
  )
}
